# pytest.ini
[pytest]
# 指定测试文件查找路径
testpaths = tests
# 添加项目根目录到 Python 路径
pythonpath = .
# 添加自定义命令行选项（可选）
addopts = -v --strict-markers --alluredir=allure-results
# 设置日志级别（可选）
log_cli = true
log_cli_level = INFO
base_url = http://10.10.27.171:7070